project:
  type: website
  resources: 
   - cv.pdf

website:
  title: Andrew Darwin
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: courses.qmd
        text: Coursework


  page-footer: 
    right: "&copy, 2024, Andrew James Darwin"
    background: "lightgrey"


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute: 
  freeze: auto

