project:
  type: website
  resources: 
   - cv.pdf

website:
  title: Andrew Darwin
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Information

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute: 
  freeze: auto

